export const LOAD_NEWS = 'LOAD_NEWS';
export const LOAD_ARTICLE = 'LOAD_ARTICLE';
export const POST_ARTICLE = 'POST_ARTICLE';
export const SET_LOADING = 'SET_LOADING';
export const CLEAR_ALL_DATA = 'CLEAR_ALL_DATA';
export const DELETE_ARTICLE = 'DELETE_ARTICLE';
export const DELETE_ARTICLE_SUCCESS = 'DELETE_ARTICLE_SUCCESS';
export const DELETE_ARTICLE_ERROR = 'DELETE_ARTICLE_ERROR';
