<template>
  <div id="personal-data" class="personal-data">
    <p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt; text-align: center;"><strong><span style="font-size: 12pt; font-family: Arial; color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">ПОЛИТИКА КОНФИДЕНЦИАЛЬНОСТИ</span></strong></p>
    <p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt; text-align: center;"><strong><span style="font-size: 12pt; font-family: Arial; color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">(PRIVACY POLICY)</span></strong></p>
    <p style="line-height: 1.7999999999999998; margin-top: 0pt; margin-bottom: 0pt; text-align: justify;"><span style="font-size: 10pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Последнее обновление: &ldquo;06&rdquo; апреля 2018 года</span></p>
    <p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt; text-align: center;">&nbsp;</p>
    <p style="line-height: 1.7999999999999998; margin-top: 0pt; margin-bottom: 0pt; text-indent: 35.43307086614173pt; text-align: justify;"><span style="font-size: 12pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Настоящая &nbsp;Политика конфиденциальности &nbsp;персональных данных (далее - Политика &nbsp;&nbsp;конфиденциальности) действует в отношении &nbsp;всей информации, размещенной на сайте в сети Интернет по адресу: https://sbinvest.pro (далее - Сайт), которую посетители Сайта и иные лица, могут &nbsp;получить о Пользователе во время использования Сайта, его сервисов, программ и продуктов.</span></p>
    <p style="line-height: 1.7999999999999998; margin-top: 0pt; margin-bottom: 0pt; text-align: justify;"><span style="font-size: 12pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;В любое время по нашему собственному усмотрению мы вправе вносить изменения в настоящую Политику конфиденциальности. Любые редакции настоящего документа будут публиковаться на главной странице нашего Сайта. Для ознакомления с любыми изменениями, которые могут быть внесены в настоящую Политику конфиденциальности, Пользователь должен периодически посещать наш Сайт. Дальнейшее использование Сайта, означает согласие Пользователя с любыми такими изменениями настоящей Политики конфиденциальности. </span></p>
    <p style="line-height: 1.7999999999999998; margin-top: 0pt; margin-bottom: 0pt; text-align: justify;"><span style="font-size: 12pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> &nbsp;&nbsp;&nbsp;В случае не согласия с настоящей Политикой конфиденциальности, Пользователь не имеет права на использование нашего Сайта и должен немедленно прекратить работу с Сайтом, его Сервисами, программами и продуктами. </span></p>
    <p style="line-height: 1.7999999999999998; margin-top: 0pt; margin-bottom: 0pt; text-align: justify;"><span style="font-size: 12pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> &nbsp;&nbsp;&nbsp;Сайт http:// представлен компанией ООО &ldquo;Инвест-Технологии&rdquo;, зарегистрированной в Российской Федерации, Республика Карелия, город Петрозаводск, а равно оператор по обработке персональных данных (далее &ndash; Компания). &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></p>
    <p style="line-height: 1.7999999999999998; margin-top: 0pt; margin-bottom: 0pt; text-align: justify;"><span style="font-size: 12pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> &nbsp;&nbsp;&nbsp;&nbsp;Правила использования информации, размещенной на Сайте (далее &ndash; Соглашение об использовании Сайта), устанавливаются отдельно.</span></p>
    <ol>
      <li style="line-height: 1.7999999999999998; margin-top: 0pt; margin-bottom: 0pt; text-indent: 35pt; text-align: center;"><strong><span style="font-size: 12pt; font-family: Arial; color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> ОБЩИЕ ПОЛОЖЕНИЯ</span></strong></li>
    </ol>
    <p style="line-height: 1.7999999999999998; margin-top: 0pt; margin-bottom: 0pt; text-indent: 35.43307086614173pt; text-align: justify;"><span style="font-size: 12pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Посещая наш Сайт, Пользователь может предоставлять нам информацию двух видов: персональные данные, которые добровольно раскрываются Пользователем и сбор которых осуществляется в индивидуальном порядке; а также информацию, которая собирается автоматически во время использования нашего Сайта или сервисов, доступных на нашем Сайте (далее - Информация).</span></p>
    <p style="line-height: 1.7999999999999998; margin-top: 0pt; margin-bottom: 0pt; text-indent: 35pt; text-align: justify;"><span style="font-size: 12pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">1.1. В рамках настоящей Политики под персональной информацией Пользователя понимаются:</span></p>
    <p style="line-height: 1.7999999999999998; margin-top: 0pt; margin-bottom: 0pt; text-indent: 35pt; text-align: justify;"><span style="font-size: 12pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">1.1.1. Персональная информация, которую Пользователь предоставляет о себе самостоятельно при регистрации (создании учетной записи) или в процессе использования Сервисов, включая персональные данные Пользователя. Обязательная для предоставления Сервисов информация помечена специальным образом. Иная информация предоставляется Пользователем на его усмотрение.</span></p>
    <p style="line-height: 1.7999999999999998; margin-top: 0pt; margin-bottom: 0pt; text-indent: 35.43307086614173pt; text-align: justify;"><span style="font-size: 12pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">1.1.2. Данные, которые автоматически передаются сервисам Сайта в процессе их использования с помощью установленного на устройстве Пользователя программного обеспечения, в том числе IP-адрес, данные файлов cookie, информация о браузере Пользователя (или иной программе, с помощью которой осуществляется доступ к сервисам), технические характеристики оборудования и программного обеспечения, используемых Пользователем, дата и время доступа к сервисам, адреса запрашиваемых страниц и иная подобная информация.</span></p>
    <p style="line-height: 1.7999999999999998; margin-top: 0pt; margin-bottom: 0pt; text-indent: 35pt; text-align: justify;"><span style="font-size: 12pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">1.1.3. Иная информация о Пользователе, обработка которой предусмотрена Соглашением об использовании Сайта.</span></p>
    <p style="line-height: 1.7999999999999998; margin-top: 0pt; margin-bottom: 0pt; text-indent: 35pt; text-align: justify;"><span style="font-size: 12pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">1.1.4. Настоящая Политика конфиденциальности применяется только к Сайту. Сайт &nbsp;не контролирует и не несет ответственности за сайты третьих лиц, на которые Пользователь может перейти по ссылкам, доступным на Сайте.</span></p>
    <ol start="2">
      <li style="line-height: 1.7999999999999998; margin-top: 0pt; margin-bottom: 0pt; text-indent: 35pt; text-align: center;"><strong><span style="font-size: 12pt; font-family: Arial; color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> ЦЕЛИ ОБРАБОТКИ ПЕРСОНАЛЬНОЙ ИНФОРМАЦИИ ПОЛЬЗОВАТЕЛЕЙ</span></strong></li>
    </ol>
    <p style="line-height: 1.7999999999999998; margin-top: 0pt; margin-bottom: 0pt; text-indent: 35pt; text-align: justify;"><span style="font-size: 12pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">2.1. Сайт собирает и хранит только ту персональную информацию, которая необходима для предоставления сервисов или исполнения соглашений и договоров с Пользователем, за исключением случаев, когда законодательством предусмотрено обязательное хранение персональной информации в течение определенного законом срока.</span></p>
    <p style="line-height: 1.7999999999999998; margin-top: 0pt; margin-bottom: 0pt; text-indent: 35pt; text-align: justify;"><span style="font-size: 12pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">2.2. Персональную информацию Пользователя Сайт обрабатывает в следующих целях:</span></p>
    <p style="line-height: 1.7999999999999998; margin-top: 0pt; margin-bottom: 0pt; text-indent: 35pt; text-align: justify;"><span style="font-size: 12pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">2.2.1. Идентификации Пользователя, зарегистрированного на Сайте.</span></p>
    <p style="line-height: 1.7999999999999998; margin-top: 0pt; margin-bottom: 0pt; text-indent: 35pt; text-align: justify;"><span style="font-size: 12pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">2.2.2. Предоставления Пользователю доступа к персонализированным ресурсам Сайта.</span></p>
    <p style="line-height: 1.7999999999999998; margin-top: 0pt; margin-bottom: 0pt; text-indent: 35pt; text-align: justify;"><span style="font-size: 12pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">2.2.3. Установления с Пользователем обратной связи, включая направление уведомлений, запросов, касающихся использования Сайта, оказания услуг, обработку запросов и заявок от Пользователя.</span></p>
    <p style="line-height: 1.7999999999999998; margin-top: 0pt; margin-bottom: 0pt; text-indent: 35pt; text-align: justify;"><span style="font-size: 12pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">2.2.4. Определения места нахождения Пользователя для обеспечения безопасности, предотвращения мошенничества.</span></p>
    <p style="line-height: 1.7999999999999998; margin-top: 0pt; margin-bottom: 0pt; text-indent: 35pt; text-align: justify;"><span style="font-size: 12pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">2.2.5. Подтверждения достоверности и полноты персональных данных, предоставленных Пользователем.</span></p>
    <p style="line-height: 1.7999999999999998; margin-top: 0pt; margin-bottom: 0pt; text-indent: 35pt; text-align: justify;"><span style="font-size: 12pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">2.2.6. Создания учетной записи, если Пользователь дал согласие на создание учетной записи.</span></p>
    <p style="line-height: 1.7999999999999998; margin-top: 0pt; margin-bottom: 0pt; text-indent: 35pt; text-align: justify;"><span style="font-size: 12pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">2.2.7. Уведомления Пользователя Сайта о возникших изменениях, независимо от характера и направленности.</span></p>
    <p style="line-height: 1.7999999999999998; margin-top: 0pt; margin-bottom: 0pt; text-indent: 35pt; text-align: justify;"><span style="font-size: 12pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">2.2.8. Предоставления Пользователю эффективной клиентской и технической поддержки при возникновении проблем, связанных с использованием Сайта.</span></p>
    <p style="line-height: 1.7999999999999998; margin-top: 0pt; margin-bottom: 0pt; text-indent: 35pt; text-align: justify;"><span style="font-size: 12pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">2.2.9. Осуществления рекламной деятельности с согласия Пользователя.</span></p>
    <ol start="3">
      <li style="line-height: 1.7999999999999998; margin-top: 0pt; margin-bottom: 0pt; text-indent: 35pt; text-align: center;"><strong><span style="font-size: 12pt; font-family: Arial; color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> УСЛОВИЯ ОБРАБОТКИ ПЕРСОНАЛЬНОЙ ИНФОРМАЦИИ ПОЛЬЗОВАТЕЛЕЙ И ЕЕ ПЕРЕДАЧИ ТРЕТЬИМ ЛИЦАМ</span></strong></li>
    </ol>
    <p style="line-height: 1.7999999999999998; margin-top: 0pt; margin-bottom: 0pt; text-indent: 35pt; text-align: justify;"><span style="font-size: 12pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">3.1. Сайт хранит персональную информацию Пользователей в соответствии с внутренними регламентами конкретных сервисов.</span></p>
    <p style="line-height: 1.7999999999999998; margin-top: 0pt; margin-bottom: 0pt; text-indent: 35pt; text-align: justify;"><span style="font-size: 12pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">3.2. В отношении персональной информации Пользователя сохраняется ее конфиденциальность, кроме случаев добровольного предоставления Пользователем информации о себе для общего доступа неограниченному кругу лиц. При использовании отдельных сервисов Пользователь соглашается с тем, что определенная часть его персональной информации становится общедоступной.</span></p>
    <p style="line-height: 1.7999999999999998; margin-top: 0pt; margin-bottom: 0pt; text-indent: 35pt; text-align: justify;"><span style="font-size: 12pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">3.3. Сайт вправе передать персональную информацию Пользователя третьим лицам в следующих случаях:</span></p>
    <p style="line-height: 1.7999999999999998; margin-top: 0pt; margin-bottom: 0pt; text-indent: 35pt; text-align: justify;"><span style="font-size: 12pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">3.3.1. Пользователь выразил согласие на такие действия.</span></p>
    <p style="line-height: 1.7999999999999998; margin-top: 0pt; margin-bottom: 0pt; text-indent: 35pt; text-align: justify;"><span style="font-size: 12pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">3.3.2. Передача необходима для использования Пользователем определенного сервиса либо для исполнения определенного соглашения или договора с Пользователем.</span></p>
    <p style="line-height: 1.7999999999999998; margin-top: 0pt; margin-bottom: 0pt; text-indent: 35pt; text-align: justify;"><span style="font-size: 12pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">3.3.4. Передача предусмотрена российским или иным применимым законодательством в рамках установленной законодательством процедуры.</span></p>
    <p style="line-height: 1.7999999999999998; margin-top: 0pt; margin-bottom: 0pt; text-indent: 35pt; text-align: justify;"><span style="font-size: 12pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">3.3.5. В случае продажи Сайта к приобретателю переходят все обязательства по соблюдению условий настоящей Политики применительно к полученной им персональной информации.</span></p>
    <p style="line-height: 1.7999999999999998; margin-top: 0pt; margin-bottom: 0pt; text-indent: 35pt; text-align: justify;"><span style="font-size: 12pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">3.4. Обработка персональных данных Пользователя осуществляется без ограничения срока любым законным способом, в том числе в информационных системах персональных данных с использованием средств автоматизации или без использования таких средств. Обработка персональных данных Пользователей осуществляется в соответствии с действующим законодательством.</span></p>
    <p style="line-height: 1.7999999999999998; margin-top: 0pt; margin-bottom: 0pt; text-indent: 35pt; text-align: justify;"><span style="font-size: 12pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">3.5. При утрате или разглашении персональных данных Компания информирует Пользователя об утрате или разглашении персональных данных.</span></p>
    <p style="line-height: 1.7999999999999998; margin-top: 0pt; margin-bottom: 0pt; text-indent: 35pt; text-align: justify;"><span style="font-size: 12pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">3.6. Компания принимает необходимые организационные и технические меры для защиты персональной информации Пользователя от неправомерного или случайного доступа, уничтожения, изменения, блокирования, копирования, распространения, а также от иных неправомерных действий третьих лиц.</span></p>
    <p style="line-height: 1.7999999999999998; margin-top: 0pt; margin-bottom: 0pt; text-indent: 35pt; text-align: justify;"><span style="font-size: 12pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">3.7. Компания совместно с Пользователем принимает все необходимые меры по предотвращению убытков или иных отрицательных последствий, вызванных утратой или разглашением персональных данных Пользователя.</span></p>
    <ol start="4">
      <li style="line-height: 1.7999999999999998; margin-top: 0pt; margin-bottom: 0pt; text-indent: 35pt; text-align: center;"><strong><span style="font-size: 12pt; font-family: Arial; color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> ОБЯЗАТЕЛЬСТВА СТОРОН</span></strong></li>
    </ol>
    <p style="line-height: 1.7999999999999998; margin-top: 0pt; margin-bottom: 0pt; text-indent: 35pt; text-align: justify;"><span style="font-size: 12pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">4.1. Пользователь обязан:</span></p>
    <p style="line-height: 1.7999999999999998; margin-top: 0pt; margin-bottom: 0pt; text-indent: 35pt; text-align: justify;"><span style="font-size: 12pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">4.1.1. Предоставить информацию о персональных данных, необходимую для пользования Сайтом.</span></p>
    <p style="line-height: 1.7999999999999998; margin-top: 0pt; margin-bottom: 0pt; text-indent: 35pt; text-align: justify;"><span style="font-size: 12pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">4.1.2. Обновлять, дополнять предоставленную информацию о персональных данных в случае изменения данной информации.</span></p>
    <p style="line-height: 1.7999999999999998; margin-top: 0pt; margin-bottom: 0pt; text-indent: 35pt; text-align: justify;"><span style="font-size: 12pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">4.2. Компания обязана:</span></p>
    <p style="line-height: 1.7999999999999998; margin-top: 0pt; margin-bottom: 0pt; text-indent: 35pt; text-align: justify;"><span style="font-size: 12pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">4.2.1. Использовать полученную информацию исключительно для целей, указанных в настоящей Политике конфиденциальности.</span></p>
    <p style="line-height: 1.7999999999999998; margin-top: 0pt; margin-bottom: 0pt; text-indent: 35pt; text-align: justify;"><span style="font-size: 12pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">4.2.2. Обеспечить хранение конфиденциальной информации в тайне, не разглашать без предварительного письменного разрешения Пользователя, а также не осуществлять продажу, обмен, опубликование либо разглашение иными возможными способами переданных персональных данных Пользователя, за исключением предусмотренных настоящей Политикой конфиденциальности.</span></p>
    <p style="line-height: 1.7999999999999998; margin-top: 0pt; margin-bottom: 0pt; text-indent: 35pt; text-align: justify;"><span style="font-size: 12pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">4.2.3. Принимать меры предосторожности для защиты конфиденциальности персональных данных Пользователя согласно порядку, обычно используемому для защиты такого рода информации в существующем деловом обороте.</span></p>
    <p style="line-height: 1.7999999999999998; margin-top: 0pt; margin-bottom: 0pt; text-indent: 35pt; text-align: justify;"><span style="font-size: 12pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">4.2.4. Осуществить блокирование персональных данных, относящихся к соответствующему Пользователю, с момента обращения или запроса Пользователя, или его законного представителя либо уполномоченного органа по защите прав субъектов персональных данных на период проверки в случае выявления недостоверных персональных данных или неправомерных действий.</span></p>
    <ol start="5">
      <li style="line-height: 1.7999999999999998; margin-top: 0pt; margin-bottom: 0pt; text-indent: 35pt; text-align: center;"><strong><span style="font-size: 12pt; font-family: Arial; color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> ОТВЕТСТВЕННОСТЬ СТОРОН</span></strong></li>
    </ol>
    <p style="line-height: 1.7999999999999998; margin-top: 0pt; margin-bottom: 0pt; text-indent: 35pt; text-align: justify;"><span style="font-size: 12pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">5.1. В случае утраты или разглашения конфиденциальной информации Компания не несёт ответственности, если данная конфиденциальная информация:</span></p>
    <p style="line-height: 1.7999999999999998; margin-top: 0pt; margin-bottom: 0pt; text-indent: 35pt; text-align: justify;"><span style="font-size: 12pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">5.1.1. Стала публичным достоянием до её утраты или разглашения.</span></p>
    <p style="line-height: 1.7999999999999998; margin-top: 0pt; margin-bottom: 0pt; text-indent: 35pt; text-align: justify;"><span style="font-size: 12pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">5.1.2. Была получена от третьей стороны до момента её получения Компанией.</span></p>
    <p style="line-height: 1.7999999999999998; margin-top: 0pt; margin-bottom: 0pt; text-indent: 35pt; text-align: justify;"><span style="font-size: 12pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">5.1.3. Была разглашена с согласия Пользователя.</span></p>
    <ol start="6">
      <li style="line-height: 1.7999999999999998; margin-top: 0pt; margin-bottom: 0pt; text-indent: 35pt; text-align: center;"><strong><span style="font-size: 12pt; font-family: Arial; color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> РАЗРЕШЕНИЕ СПОРОВ</span></strong></li>
    </ol>
    <p style="line-height: 1.7999999999999998; margin-top: 0pt; margin-bottom: 0pt; text-indent: 35pt; text-align: justify;"><span style="font-size: 12pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">6.1. До обращения в суд с иском по спорам, возникающим из отношений между Пользователем Сайта и Компанией, обязательным является предъявление претензии (письменного предложения о добровольном урегулировании спора).</span></p>
    <p style="line-height: 1.7999999999999998; margin-top: 0pt; margin-bottom: 0pt; text-indent: 35pt; text-align: justify;"><span style="font-size: 12pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">6.2. Получатель претензии в течение 14 календарных дней со дня получения претензии письменно уведомляет заявителя претензии о результатах рассмотрения претензии.</span></p>
    <p style="line-height: 1.7999999999999998; margin-top: 0pt; margin-bottom: 0pt; text-indent: 35pt; text-align: justify;"><span style="font-size: 12pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">6.3. При недостижении соглашения спор будет передан на рассмотрение в судебные органы в соответствии с действующим законодательством.</span></p>
    <p style="line-height: 1.7999999999999998; margin-top: 0pt; margin-bottom: 0pt; text-indent: 35pt; text-align: justify;"><span style="font-size: 12pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">6.4. К настоящей Политике конфиденциальности и отношениям между Пользователем и Компании применяется действующее законодательство Российской Федерации до тех пор, пока находится в рамках его регулирования.</span></p>
    <ol start="7">
      <li style="line-height: 1.7999999999999998; margin-top: 0pt; margin-bottom: 0pt; text-indent: 35pt; text-align: center;"><strong><span style="font-size: 12pt; font-family: Arial; color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> ДОПОЛНИТЕЛЬНЫЕ УСЛОВИЯ</span></strong></li>
    </ol>
    <p style="line-height: 1.7999999999999998; margin-top: 0pt; margin-bottom: 0pt; text-indent: 35pt; text-align: justify;"><span style="font-size: 12pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">7.1. Компания вправе вносить изменения в настоящую Политику конфиденциальности без согласия Пользователя.</span></p>
    <p style="line-height: 1.7999999999999998; margin-top: 0pt; margin-bottom: 0pt; text-indent: 35pt; text-align: justify;"><span style="font-size: 12pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">7.2. Новая Политика конфиденциальности вступает в силу с момента ее размещения на Сайте, если иное не предусмотрено новой редакцией Политики конфиденциальности.</span></p>
    <p style="line-height: 1.7999999999999998; margin-top: 0pt; margin-bottom: 0pt; text-indent: 35pt; text-align: justify;"><span style="font-size: 12pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">7.3. Все предложения или вопросы по настоящей Политике конфиденциальности следует сообщать согласно контактным данным, размещенным на Сайте.</span></p>
    <p style="line-height: 1.7999999999999998; margin-top: 0pt; margin-bottom: 0pt; text-indent: 35pt; text-align: justify;"><span style="font-size: 12pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">7.4. Действующая Политика конфиденциальности размещена на странице по адресу:</span></p>
    <p style="line-height: 1.7999999999999998; margin-top: 0pt; margin-bottom: 0pt; text-indent: 35pt; text-align: justify;"><span style="font-size: 12pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">7.5. Настоящий Сайт может содержать ссылки на другие сайты третьих лиц, которые могут собирать личную информацию о Пользователе. В случае перехода на другой сайт, Пользователь покидает данный Сайт, и условия настоящей Политики конфиденциальности не будут применяться к использованию Пользователем сторонних сайтов и действиям Пользователя на них. Пользователь должен проконсультироваться с политиками конфиденциальности других сайтов, поскольку мы не контролируем их и не несем ответственности за любую информацию, которая была передана или собрана этими третьими лицами.</span></p>
    <p style="line-height: 1.7999999999999998; margin-top: 0pt; margin-bottom: 0pt; text-indent: 35pt; text-align: justify;"><span style="font-size: 12pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Если у Вас возникли вопросы в отношении настоящей Политики конфиденциальности, пишите нам на электронный адрес: </span><a style="text-decoration: none;" href="mailto:a_belonogov@mail.ru"><span style="font-size: 12pt; font-family: Arial; color: #1155cc; background-color: #ffffff; font-weight: 400; font-variant: normal; text-decoration: underline; -webkit-text-decoration-skip: none; text-decoration-skip-ink: none; vertical-align: baseline; white-space: pre-wrap;">a_belonogov@mail.ru</span></a><span style="font-size: 12pt; font-family: Arial; color: #0590b3; background-color: #ffffff; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">. </span></p>
    <p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt; text-align: center;"><br /><br /><br /></p>
  </div>
</template>

<style lang="scss" src="./style.scss" scoped></style>

<script>
  export default {
    name: 'PersonalData'
  };
</script>
